version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: youtube_redis
    restart: always
    volumes:
      - redis_data:/data

  api:
    build: ./api
    container_name: youtube_api
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - redis
    volumes:
      - ./downloaded:/data/downloads
      - ./public:/data/public

  worker:
    build: ./worker
    container_name: youtube_worker
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./downloaded:/data/downloads

volumes:
  redis_data:
